version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: cleaning-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: cleaning-frontend
    ports:
      - "4003:80"
    restart: always