version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4004:5000"
    # env_file:
    #   - ./backend/.env
    environment:
      - MONGO_URI=mongodb://localhost:27017/cleaning-app
      - JWT_SECRET=skjfhsd8723**!@YASDKjhfdas9823
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "4003:80"
    depends_on:
      - backend
    restart: always
