version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4004:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "4003:80"
    depends_on:
      - backend
    restart: always